{
    "config": {
        "abort": {
            "already_configured": "El dispositivo ya est\u00e1 configurado",
            "reauth_successful": "La autenticaci\u00f3n se volvi\u00f3 a realizar correctamente",
            "reconfigure_successful": "Se volvi\u00f3 a configurar correctamente"
        },
        "error": {
            "cannot_connect": "No se pudo conectar",
            "invalid_auth": "Autenticaci\u00f3n no v\u00e1lida",
            "unknown": "Error inesperado"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Contrase\u00f1a",
                    "username": "Nombre de usuario"
                },
                "title": "Autenticaci\u00f3n caducada para {name}"
            },
            "reconfigure_confirm": {
                "data": {
                    "host": "Host",
                    "password": "Contrase\u00f1a",
                    "port": "Puerto",
                    "ssl": "Utiliza un certificado SSL",
                    "username": "Nombre de usuario",
                    "verify_ssl": "Verificar el certificado SSL"
                },
                "data_description": {
                    "host": "El nombre de host o la direcci\u00f3n IP del dispositivo que ejecuta tu instancia de pyLoad.",
                    "port": "pyLoad utiliza el puerto 8000 por defecto."
                }
            },
            "user": {
                "data": {
                    "host": "Host",
                    "name": "Nombre",
                    "password": "Contrase\u00f1a",
                    "port": "Puerto",
                    "ssl": "Utiliza un certificado SSL",
                    "username": "Nombre de usuario",
                    "verify_ssl": "Verificar el certificado SSL"
                },
                "data_description": {
                    "host": "El nombre de host o la direcci\u00f3n IP del dispositivo que ejecuta tu instancia de pyLoad.",
                    "name": "El nombre que usar\u00e1 para tu instancia de pyLoad en Home Assistant",
                    "port": "pyLoad utiliza el puerto 8000 por defecto."
                }
            }
        }
    },
    "entity": {
        "button": {
            "abort_downloads": {
                "name": "Abortar todas las descargas en curso"
            },
            "delete_finished": {
                "name": "Eliminar archivos/paquetes terminados"
            },
            "restart": {
                "name": "Reiniciar el n\u00facleo de pyload"
            },
            "restart_failed": {
                "name": "Reiniciar todos los archivos fallidos"
            }
        },
        "sensor": {
            "active": {
                "name": "Descargas activas"
            },
            "free_space": {
                "name": "Espacio libre"
            },
            "queue": {
                "name": "Descargas en cola"
            },
            "speed": {
                "name": "Velocidad"
            },
            "total": {
                "name": "Descargas totales"
            }
        },
        "switch": {
            "download": {
                "name": "Pausa/Reanudar cola"
            },
            "reconnect": {
                "name": "Reconexi\u00f3n autom\u00e1tica"
            }
        }
    },
    "exceptions": {
        "service_call_auth_exception": {
            "message": "No se pudo enviar el comando a pyLoad debido a un error de autenticaci\u00f3n, int\u00e9ntalo de nuevo m\u00e1s tarde"
        },
        "service_call_exception": {
            "message": "No se pudo enviar el comando a pyLoad debido a un error de conexi\u00f3n, int\u00e9ntalo de nuevo m\u00e1s tarde"
        },
        "setup_authentication_exception": {
            "message": "Error de autenticaci\u00f3n para {username}, verifica tus credenciales de inicio de sesi\u00f3n"
        },
        "setup_parse_exception": {
            "message": "No se pudo analizar los datos de la API pyLoad, int\u00e9ntalo de nuevo m\u00e1s tarde"
        },
        "setup_request_exception": {
            "message": "No se pudo conectar y recuperar datos de la API pyLoad, int\u00e9ntalo de nuevo m\u00e1s tarde"
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "Se va a eliminar la configuraci\u00f3n de pyLoad mediante YAML, pero hubo un error de conexi\u00f3n al intentar importar la configuraci\u00f3n YAML. \n\nPor favor, verifica que tengas una conexi\u00f3n estable a Internet y reinicia Home Assistant para intentarlo de nuevo o elimina la configuraci\u00f3n YAML de pyLoad de tu archivo configuration.yaml y contin\u00faa [configurando la integraci\u00f3n]({url}) manualmente.",
            "title": "Error al importar la configuraci\u00f3n YAML de pyLoad"
        },
        "deprecated_yaml_import_issue_invalid_auth": {
            "description": "Se va a eliminar la configuraci\u00f3n de pyLoad mediante YAML, pero hubo un error de autenticaci\u00f3n al intentar importar la configuraci\u00f3n YAML. \n\nCorrige la configuraci\u00f3n YAML y reinicia Home Assistant para intentarlo de nuevo o elimina la configuraci\u00f3n YAML de pyLoad de tu archivo configuration.yaml y contin\u00faa [configurando la integraci\u00f3n]({url}) manualmente.",
            "title": "Error al importar la configuraci\u00f3n YAML de pyLoad"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "Se va a eliminar la configuraci\u00f3n de pyLoad mediante YAML, pero hubo un error desconocido al intentar importar la configuraci\u00f3n YAML. \n\nAseg\u00farate de que la configuraci\u00f3n YAML sea correcta y reinicia Home Assistant para intentarlo de nuevo o elimina la configuraci\u00f3n YAML de pyLoad de tu archivo configuration.yaml y contin\u00faa [configurando la integraci\u00f3n]({url}) manualmente.",
            "title": "Error al importar la configuraci\u00f3n YAML de pyLoad"
        }
    }
}