{
    "config": {
        "abort": {
            "already_configured": "Az eszk\u00f6z m\u00e1r konfigur\u00e1lva van",
            "reauth_successful": "Az \u00fajrahiteles\u00edt\u00e9s sikeres volt.",
            "reconfigure_successful": "\u00dajrakonfigur\u00e1l\u00e1s sikeres volt"
        },
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_auth": "\u00c9rv\u00e9nytelen hiteles\u00edt\u00e9s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Jelsz\u00f3",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v"
                },
                "title": "A(z) {name} hiteles\u00edt\u00e9se lej\u00e1rt"
            },
            "reconfigure_confirm": {
                "data": {
                    "host": "Hoszt",
                    "password": "Jelsz\u00f3",
                    "port": "Port",
                    "ssl": "SSL tan\u00fas\u00edtv\u00e1nyt haszn\u00e1l",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v",
                    "verify_ssl": "SSL-tan\u00fas\u00edtv\u00e1ny ellen\u0151rz\u00e9se"
                },
                "data_description": {
                    "host": "A pyLoad p\u00e9ld\u00e1nyt futtat\u00f3 eszk\u00f6z hosztneve vagy IP-c\u00edme.",
                    "port": "A pyLoad alap\u00e9rtelmez\u00e9s szerint a 8000-es portot haszn\u00e1lja."
                }
            },
            "user": {
                "data": {
                    "host": "Hoszt",
                    "name": "Elnevez\u00e9s",
                    "password": "Jelsz\u00f3",
                    "port": "Port",
                    "ssl": "SSL tan\u00fas\u00edtv\u00e1nyt haszn\u00e1l",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v",
                    "verify_ssl": "SSL-tan\u00fas\u00edtv\u00e1ny ellen\u0151rz\u00e9se"
                },
                "data_description": {
                    "host": "A pyLoad p\u00e9ld\u00e1nyt futtat\u00f3 eszk\u00f6z hosztneve vagy IP-c\u00edme.",
                    "name": "A pyLoad p\u00e9ld\u00e1ny\u00e1nak neve a Home Assistantban",
                    "port": "A pyLoad alap\u00e9rtelmez\u00e9s szerint a 8000-es portot haszn\u00e1lja."
                }
            }
        }
    },
    "entity": {
        "button": {
            "abort_downloads": {
                "name": "Minden fut\u00f3 let\u00f6lt\u00e9s megszak\u00edt\u00e1sa"
            },
            "delete_finished": {
                "name": "Befejezett f\u00e1jlok/csomagok t\u00f6rl\u00e9se"
            },
            "restart": {
                "name": "A pyLoad mag \u00fajraind\u00edt\u00e1sa"
            },
            "restart_failed": {
                "name": "Az \u00f6sszes sikertelen f\u00e1jl \u00fajraind\u00edt\u00e1sa"
            }
        },
        "sensor": {
            "active": {
                "name": "Akt\u00edv let\u00f6lt\u00e9sek"
            },
            "free_space": {
                "name": "Szabad hely"
            },
            "queue": {
                "name": "Let\u00f6lt\u00e9sek v\u00e1r\u00f3list\u00e1n"
            },
            "speed": {
                "name": "Sebess\u00e9g"
            },
            "total": {
                "name": "\u00d6sszes let\u00f6lt\u00e9s"
            }
        },
        "switch": {
            "download": {
                "name": "V\u00e1r\u00f3lista sz\u00fcneteltet\u00e9se/folytat\u00e1sa"
            },
            "reconnect": {
                "name": "Automatikus \u00fajracsatlakoz\u00e1s"
            }
        }
    },
    "exceptions": {
        "service_call_auth_exception": {
            "message": "Nem siker\u00fclt parancsot k\u00fcldeni a pyLoad fel\u00e9 hiteles\u00edt\u00e9si hiba miatt, pr\u00f3b\u00e1lja meg k\u00e9s\u0151bb \u00fajra"
        },
        "service_call_exception": {
            "message": "Nem siker\u00fclt parancsot k\u00fcldeni a pyLoad fel\u00e9 kapcsolat hiba miatt, pr\u00f3b\u00e1lja meg k\u00e9s\u0151bb \u00fajra"
        },
        "setup_authentication_exception": {
            "message": "{username} hiteles\u00edt\u00e9se nem siker\u00fclt, ellen\u0151rizze bejelentkez\u00e9si adatait"
        },
        "setup_parse_exception": {
            "message": "Nem siker\u00fclt feldolgozni a pyLoad API-b\u00f3l sz\u00e1rmaz\u00f3 adatokat, pr\u00f3b\u00e1lja meg k\u00e9s\u0151bb \u00fajra"
        },
        "setup_request_exception": {
            "message": "Nem siker\u00fclt csatlakozni \u00e9s adatokat lek\u00e9rni a pyLoad API-b\u00f3l, pr\u00f3b\u00e1lja meg k\u00e9s\u0151bb \u00fajra"
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "A pyLoad YAML alap\u00fa konfigur\u00e1ci\u00f3j\u00e1t elt\u00e1vol\u00edt\u00e1sra ker\u00fcl, de egy kapcsolat hiba t\u00f6rt\u00e9nt a YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sakor.\n\nK\u00e9rj\u00fck, ellen\u0151rizze, hogy stabil internetkapcsolattal rendelkezik-e, majd ind\u00edtsa \u00fajra a Home Assistant rendszert \u00e9s pr\u00f3b\u00e1lja meg \u00fajra vagy t\u00e1vol\u00edtsa el a pyLoad YAML konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l \u00e9s folytassa az integr\u00e1ci\u00f3 [k\u00e9zi be\u00e1ll\u00edt\u00e1s\u00e1val]({url}).",
            "title": "A pyLoad YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sikertelen volt"
        },
        "deprecated_yaml_import_issue_invalid_auth": {
            "description": "A pyLoad YAML alap\u00fa konfigur\u00e1ci\u00f3j\u00e1t elt\u00e1vol\u00edt\u00e1sra ker\u00fcl, de egy hiteles\u00edt\u00e9si hiba t\u00f6rt\u00e9nt a YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sakor.\n\nJav\u00edtsa ki a YAML konfigur\u00e1ci\u00f3t, majd ind\u00edtsa \u00fajra a Home Assistant rendszert \u00e9s pr\u00f3b\u00e1lja meg \u00fajra vagy t\u00e1vol\u00edtsa el a pyLoad YAML konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l \u00e9s folytassa az integr\u00e1ci\u00f3 [k\u00e9zi be\u00e1ll\u00edt\u00e1s\u00e1val]({url}).",
            "title": "A pyLoad YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sikertelen volt"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "A pyLoad YAML alap\u00fa konfigur\u00e1ci\u00f3j\u00e1t elt\u00e1vol\u00edt\u00e1s ker\u00fcl, de egy ismeretlen hiba t\u00f6rt\u00e9nt a YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sakor.\n\nGy\u0151z\u0151dj\u00f6n meg r\u00f3la, hogy a YAML konfigur\u00e1ci\u00f3 helyes, majd ind\u00edtsa \u00fajra a Home Assistant rendszert \u00e9s pr\u00f3b\u00e1lja meg \u00fajra vagy t\u00e1vol\u00edtsa el a pyLoad YAML konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l \u00e9s folytassa az integr\u00e1ci\u00f3 [k\u00e9zi be\u00e1ll\u00edt\u00e1s\u00e1val]({url}).",
            "title": "A pyLoad YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sikertelen volt"
        }
    }
}